rust-osdev/x86_64

src/addr.rs
src/instructions/mod.rs
src/instructions/port.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/structures/idt.rs
src/structures/mod.rs
src/structures/tss.rs

This patch enables the IDT and TSS structures. It also adds a const `zero` function to the VirtAddr struct.

Enable IDT and TSS Structures

---

src/structures/paging/recursive.rs

Operations on the RecursivePageTable (`map_to`, `unmap`, etc) now return a `MapperFlush` that must either be `flush`ed to remove the now-outdated tlb entry for the modified page or unsafely `ignore`ed.

Added return value for RecursivePageTable operations that must be used.

---

src/structures/paging/page_table.rs
src/structures/paging/recursive.rs

This adds a `remap` function to the `Mapper` trait and the `RecursivePageTable`.

Added remapping ability to RecursivePageTable

---

src/structures/idt.rs

Tiny typo fix in idt.rs

---

src/structures/idt.rs

When initializing my IDT, I am overflowing my stack because rustc first allocates the IDT (4096B) on the stack and then copies it to my actual IDT. Instead, this allocates allows one to initialize an existing IDT without additional stack space.

In-place IDT init

---

src/structures/idt.rs

Becaues I want to be able to store the `Idt` in a `static mut`.

Make Idt::new const

---

src/structures/paging/frame_alloc.rs
src/structures/paging/mod.rs
src/structures/paging/recursive.rs

I propose to more clearly separate out the notion of a Physical Frame Allocator. This PR creates a new PhysMemAllocator trait and uses it in the recursive page table. This also happens to solve a couple of compile errors around borrowing closures.
r? @phil-opp

Create a separate PhysMemAllocator trait

---

testing/src/bin/test-basic.rs

This should resolve the `panic_implementation` deprecation warning.

Switch to new panic_handler attribute

---

.travis.yml
src/instructions/interrupts.rs
src/instructions/mod.rs
src/instructions/port.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/registers/control.rs
src/registers/model_specific.rs
src/registers/rflags.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/mod.rs
src/structures/paging/mod.rs
src/structures/paging/recursive.rs
src/structures/port.rs

This ensures that the crate is buildable on all platforms. If building on non-x86_64, not all functions will be present.

Use conditional compilation for platform specific functions

---

src/structures/paging/mod.rs

Implements `PageSize` trait for `Page` itself, which allows using `Page::SIZE` to get page size without having an instance. This is really useful especially if you use type aliases to define page size constants.

Add SIZE constant for Page

---

src/instructions/interrupts.rs

Almost useless pull request to fix a typo in the incode documentation.
Btw thanks for your work, your crate really help me with my honours project.

Correct typo ("closue" instead of "closure")

---

src/instructions/port.rs
src/structures/port.rs
testing/src/bin/test-port-read-write.rs

Here's the pull request for the changes we talked about. I wasn't sure what you wanted for the documentation, so i left what was there and added one to the PortRead and PortWrite. Feel free to change it how you see fit. Let me know if you need anything changed.

Read write ports

---

Cargo.toml
Changelog.md
azure-pipelines.yml
bors.toml
src/addr.rs
src/instructions/port.rs
src/structures/paging/page_table.rs
src/structures/port.rs

Update the code to use the more general [`cast`](https://docs.rs/cast/0.2.2/cast/) crate.
This PR also adds support for bors and a check for correct `rustfmt` formatting to CI.

Use cast crate instead of usize_conversions crate

---

Changelog.md
src/structures/paging/frame_alloc.rs
src/structures/paging/mapper/mod.rs

This is a breaking change.
Fixes #69

Make FrameAllocator an unsafe trait

---

src/instructions/port.rs
testing/src/bin/test-port-read-write.rs

Change Port::read and PortReadOnly::read to take &mut self

---

src/instructions/interrupts.rs
src/instructions/mod.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/instructions/tlb.rs
src/registers/mod.rs

* Added functions for a bochs magic breakpoint and reading the instruction pointer
* Marked small single-instruction functions as `#[inline]`
* Improved the docs for the segmentation functions

Add bochs magic breakpoint, read instruction pointer, inline instructions

---

src/structures/gdt.rs

Diff should be fairly self-explanatory.

Update GDT docs, add user_data_segment function and WRITABLE flag

---

src/structures/paging/mod.rs

Just a small oversight. The `MappedPageTable` type is platform independent, so we can reexport it on all platforms.

Reexport MappedPageTable on non-x86_64 platforms too

---

Changelog.md
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mod.rs

The type wraps a `MappedPageTable` instance with a simpler interface. It uses a simple phys-to-virt offset instead of being generic over a phys-to-virt closure, which makes it easier to e.g. store the type in a `static`.
TODO:
Fixes #81

Add a new `OffsetPageTable` mapper type

---

Cargo.toml
src/instructions/random.rs

This reduces my compile times from scratch from about 215s to 160s.

Remove raw-cpuid dependency and use rdrand intrinsics

---

src/instructions/segmentation.rs
src/registers/model_specific.rs

Add `FS.Base` and `GS.Base` register support.
https://stackoverflow.com/a/11497742/2178906

Add FsBase and GsBase register support

---

src/structures/idt.rs

the interrupt handler functions are extern to allow for the special calling convention.
rust warns about using this struct with extern functions.
this patch suppresses the warning by fixing the struct layout.
i think in this case the warning is correctly pointing out that while the nested InterruptStackFrameValue is repr(C), the wrapper type is not. it seems incredibly unlikely that the compiler would do anything wrong here but adding repr(C) guards against it.
example warning:
```
Compiling libkernel v0.1.0 (/Users/cmsd2/Development/ostoo/libkernel)
warning: `extern` fn uses type `x86_64::structures::idt::InterruptStackFrame`, which is not FFI-safe
--> libkernel/src/interrupts.rs:70:18
|
70 |     stack_frame: &mut InterruptStackFrame)
|                  ^^^^^^^^^^^^^^^^^^^^^^^^ not …
```

use repr C to suppress not-ffi-safe when used with extern handler functions

---

src/structures/idt.rs

The current IDT structure doesn't provide much in the way of dynamic management.  I would like to be able to manage hardware interrupts externally. By ~~making idt.interrupts public~~ adding `slice` and `slice_mut` methods, I can return a slice of interrupt vectors to a hardware interrupt controller class so that that class can assign it's own handlers in the IDT.  Without this, the external class needs direct access to the IDT.

Add `slice` and `slice_mut` methods to IDT

---

.github/workflows/build.yml

This avoids duplicated builds when opening a pull request from a branch from this repo.

Run 'push' builds only for master branch

---

Cargo.toml
Changelog.md
src/addr.rs
src/lib.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/mod.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

This pull request introduces a new `PageTableIndex` type instead of `ux::u9`. Likewise, it introduces a new `PageOffset` instead of `ux::u12`. To migrate, you need to switch to the new types.
cc #90 

Replace `ux` dependency with custom wrapper structs

---

Changelog.md
src/structures/paging/frame_alloc.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

Fixes #88 
This pull request adds a new `UnsafePhysFrame` type that wraps a `PhysFrame`. The type is unsafe to construct and the caller must guarantee that the frame is not mapped already. This type allows to make the `map_to` and `identity_map` methods of the `Mapper` trait safe. This PR also adjust the `FrameAllocator` to use the new type.

Add new UnsafePhysFrame type and use it in Mapper::map_to

---

Changelog.md
src/structures/paging/mapper/mod.rs

See #80 for more information
I'm not quite sure whether this is a **breaking change**, but I think it is.

Make Mapper trait object safe by adding `Self: Sized` bounds on generic functions

---

Changelog.md
src/structures/idt.rs

Rename divide_by_zero field of IDT to divide_error

---

Changelog.md
src/structures/idt.rs
testing/tests/double_fault_stack_overflow.rs

Exceptions such as  double faults and machine check exceptions are classified as "abort", which means that the reported stack frame might be incorrect. It is not allowed to return from such exceptions because it could cause undefined behavior.
This pull request ensures at the type system level that double fault and machine check exceptions can never return. This way, we can prevent such undefined behavior.
Closes #97.

Introduce new diverging handler functions for exceptions classified as "abort"

---

Changelog.md
src/structures/paging/frame_alloc.rs
src/structures/paging/mod.rs

This fixes an issue in the recently released version 0.8.0 that made implementing the `FrameAllocator` trait impossible. The bug was introduced in #89.

Add required reexport for new UnusedPhysFrame type

---

src/registers/control.rs

This builds upon https://github.com/rust-osdev/x86_64/pull/92 and additionally adds documentation for the CR4 fields.

Add support for cr4 control register (with complete documentation)

---

src/instructions/port.rs

This allows the compiler to pick the version of `in` or `out` with the port number as an immediate value, if it is known at compile time.

Allow immediate port version of in/out instructions.

---

Cargo.toml
src/addr.rs
src/lib.rs
src/structures/gdt.rs
src/structures/paging/page_table.rs

Other than just adding `const` a few times, this:
- Replaces the `array_init` dependency by the `const_in_array_repeat_expressions` feature.
- Implements `VirtAddr::new_unchecked` using a multiply and divide instead of `set_bits` in an if. (Bonus: Resulting assembly is much much shorter.)

Make more functions const.

---

src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

The UnusedPhysFrame might want to be used otherwise.
Fixes https://github.com/rust-osdev/x86_64/issues/117

Return the UnusedPhysFrame on MapToError::PageAlreadyMapped

---

src/addr.rs
src/structures/paging/page_table.rs

- There are now const functions to make them: new_truncate.
- The new truncating are used in VirtAddr to avoid needless checks.
- The guarantee that they are in 0..512 and 0..4096 is documented.
- This guarantee is used in Index for PageTable to avoid needless checks.
- They are now both Into<usize>, to make it easier to use them as index.

Improve PageTableIndex and PageOffset.

---

Cargo.toml
src/addr.rs

It was only used between usize and u64 in parts of the code that were
marked with `#[cfg(target_pointer_width = "64")]`, which guarantees
usize is 64 bits.
See #90.

Remove the `cast` dependency.

---

.github/workflows/build.yml

It tried to use rustfmt from the latest nightly, but nightly doesn't always include rustfmt. By using rustup to install the default profile of nightly, it automatically looks for the latest nightly that includes rustfmt.

Fix GitHub actions to run latest available rustfmt.

---

.github/workflows/build.yml
Cargo.toml
README.md
build.rs
src/asm/asm.s
src/asm/mod.rs
src/instructions/interrupts.rs
src/instructions/mod.rs
src/instructions/port.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/instructions/tlb.rs
src/lib.rs
src/registers/control.rs
src/registers/mod.rs
src/registers/model_specific.rs
src/registers/rflags.rs
src/structures/idt.rs
src/structures/mod.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

default is "nightly"
to compile with stable rust:
x86_64 = { version = "0.9", default-features = false, features = [ "stable" ] }

enable usage with non-nightly rust

---

.github/workflows/build.yml
src/asm/mod.rs

`musl` is like `gnu` and does not add an underscore to external
function names as the real `link_name`.

asm: add target_env = "musl" to pickup the underscore asm names

---

src/addr.rs
src/instructions/interrupts.rs
src/instructions/segmentation.rs
src/lib.rs
src/registers/control.rs
src/registers/model_specific.rs
src/registers/rflags.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/paging/frame.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

I tried to mark as inlined functions that I estimated suitable, up to 4 lines of codes or distinct language statements/expressions.
I discarded operator overloadings and `new()`.
Hope that helps !

Add `#[inline]` attribute to small functions

---

src/asm/asm.s
src/asm/mod.rs
src/instructions/interrupts.rs

This function atomically enable interrupts and put the CPU to sleep by executing the `sti; hlt` instruction sequence. Since the sti instruction keeps interrupts disabled until after the immediately following instruction (called "interrupt shadow"), no interrupt can occur between the two instructions.

Add an enable_interrupts_and_hlt function that executes `sti; hlt`

---

src/addr.rs

`VirtAddr::new_unchecked` didn't behave like [the `new_unchecked` functions in `core`](https://doc.rust-lang.org/std/num/struct.NonZeroU64.html#method.new_unchecked) which just wrap the value without checks or modifications, but instead behaved like `PhysAddr::new_truncate`. This change renames it to `new_truncate`, and adds unsafe ~~`new_unchecked`~~ `new_unsafe` functions.
~~Unfortunately, that does mean it's a breaking change. However,~~ I think following this convention for "unchecked" is important to not cause confusion:
- When looking for something that fixes/truncates the address, I couldn't find any function that did that. (I didn't think that `new_unchecked` would do that.)
- When looking for something that lets me unsafely wrap an address, I used `new_unchecked`, and was …

Various improvements to VirtAddr and PhysAddr.

---

src/addr.rs

The comment (my comment) said that shifts don't work in const fns, but it appears the comment was either wrong or outdated.

In VirtAddr::new_truncate, use shift instead of mul and div.

---

src/addr.rs
src/instructions/port.rs
src/lib.rs
src/structures/idt.rs
src/structures/paging/frame.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

Many functions that can be const live in a generic context with bounds,
where `const fn` is not allowed without the "const_fn" feature.
In many places, functions duplicated becaue of this: A version with and
version without `const`.
This macro cleans that up by making it easy to define a function as
const only if possible, removing all duplication.
Also makes some more functions `const`.

Add const_fn!{} macro to make functions const without duplication.

---

src/structures/paging/frame_alloc.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/mod.rs

Make `map_to` and `update_flags` unsafe

---

src/addr.rs
src/instructions/port.rs
src/instructions/random.rs
src/instructions/segmentation.rs
src/registers/control.rs
src/registers/model_specific.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/paging/frame.rs
src/structures/paging/frame_alloc.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs
src/structures/tss.rs

I tried to follow the following rules for determining if something
should be #[inline]:
- Functions that are trivial. (E.g. implementations of `Add`, or a
trivial `new` function.)
- Functions that do not appear trivial, but would generate trivial
assembly. (E.g. functions with mostly Rust code that don't result much
generated code: `use` statements, wrapping values, bit twiddling,
`#[cfg]`, `PhantomData`, etc.)
- Functions that only call another function.
- Functions that could benefit a lot from inline optimization:
- Functions that have asserts/matches/ifs on the parameters, which are
likely constant or known to be in a certain range:
If a function starts with `assert!(param < 32)`, inlining enables
the compiler to completely optimize the check away if it already
knows the value to …

Use #[inline] everywhere.

---

src/structures/paging/frame_alloc.rs

This method should be unsafe because the caller must ensure that the passed frame is unused. Prior to #135, this was ensured by the `UnusedPhysFrame` type, which is now removed.
Reported in https://github.com/rust-osdev/x86_64/commit/8a257cc78094c4f1d7fbaaa8c1c7ba11aa62bafe#r38430639.

Make FrameDeallocator::deallocate_frame unsafe

---

src/addr.rs
src/instructions/random.rs
src/structures/gdt.rs
src/structures/paging/frame.rs
src/structures/paging/page.rs

_Edit(phil-opp)_: This is a **breaking change**.

Don't pass small trivially copyable types by reference.

---

src/structures/idt.rs

This way, no members can accidentally be forgotten.

Use Self::new() in InterruptDescriptorTable::reset().

---

src/structures/idt.rs

Without this kind of method, there is no way right now to have a dynamically-allocated IDT, and thus no real way to have a separate IDT per CPU.

Add InterruptDescriptorTable::load_unsafe

---

src/instructions/interrupts.rs
src/instructions/mod.rs
src/instructions/port.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/instructions/tlb.rs
src/lib.rs
src/registers/control.rs
src/registers/mod.rs
src/registers/model_specific.rs
src/registers/rflags.rs

Use `llvm_asm!` instead of deprecated `asm!` macro

---

src/structures/gdt.rs

Now the RPL of the returning selector is determined from whether the given descriptor has its `DPL_RING_3` set.

Return the correct RPL from GDT::add_entry()

---

src/structures/paging/frame.rs
src/structures/paging/page.rs

Currently inclusive ranges are empty when upper bound equals lower bound. Should be only empty when `start > end`.

Fix: Inclusive ranges is_empty() comparison

---

src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

It will update the parent hierarchy tables with (flags & p23_insert_flag_mask).
```rust
mapper
.map_to(
page,
frame,
PageTableFlags::PRESENT
| PageTableFlags::WRITABLE
| PageTableFlags::USER_ACCESSIBLE,
PageTableFlags::USER_ACCESSIBLE,
frame_allocator,
)
.unwrap()
.flush();
```
will update the hierarchy with `PageTableFlags::USER_ACCESSIBLE`. If the
flags would not contain `USER_ACCESSIBLE`, the hierarchy would not be
updated.
If you don't want any updates, pass `PageTableFlags::empty()` as the
mask.
Fixes #113 
_Edit (phil-opp)_: This is a **breaking change**.

Add p23_insert_flag_mask argument to mapper.map_to()

---

src/registers/model_specific.rs

Remove needless `try_into` calls

---

src/registers/control.rs

The documentation on Cr2::read refered to the Cr3 register

Correct Cr2::read documentation

---

src/addr.rs
src/lib.rs

Those two structs are exported by making the `addr` module public.
Close #162

Export PhysAddrNotValid and VirtAddrNotValid

---

README.md

uefi-rs' README.md has the badge. I thought this repo also should have one.

Add a badge to crates.io

---

src/asm/asm.s
src/asm/mod.rs
src/instructions/mod.rs

Executes the `nop` instructions, which performs no operation (i.e. does nothing).
This operation is useful to work around the LLVM bug that endless loops are illegally optimized away (see https://github.com/rust-lang/rust/issues/28728). By invoking this instruction (which is marked as volatile) in the endless loop, the compiler should no longer optimize it away.

Add a function for the `nop` instruction

---

src/structures/paging/page_table.rs

Hi! Rust compiler team member here. When the `const_fn` feature is enabled, the implementation of `PageTable::new` relies on a compiler bug to work. Specifically, `PageTableEntry::new` should not be eligible for promotion as part of an array initializer. See rust-lang/rust#75502 for more information. This bug may be fixed in the future, which would cause this crate to stop compiling.

Don't rely on promotion of `PageTableEntry::new` inside a `const fn`

---

src/addr.rs

Dereferencing to virtual address 0 is prohibited. This method is useful to prevent that.

Add `VirtAddr::is_null`

---

src/lib.rs

See: https://github.com/rust-lang/rust/issues/77134

Fix build error on latest nightly

---

Changelog.md
src/structures/gdt.rs

Add the remaining GDT flags. This now allows users to create 32-bit
and 64-bit GDTs. I also added more explanations about what each flag
does, and in which modes it is ignored.
We also add flag aliases for common cases. We then verify that these
cases match what the Linux kernel uses by default. Note that these defaults
are in some sense "mandatory" as the `syscall`/`sysenter` instructions load
constants into the various GDT registers. This also allows us
to make additional methods `const fn`.
I used [AMD64 Architecture Programmer’s Manual, Volume 2: System Programming](https://www.amd.com/system/files/TechDocs/24593.pdf)
as the main reference for this PR.
Two remaining open questions:
1. Should we set `WRITABLE` (aka Readable for code-segments) by default?
- This bit is ignored in 64-bit …

gdt: Add remaining GDT flags

---

src/instructions/port.rs
src/lib.rs

Right now we use Traits with `const fn` in two different ways:
1. `PortRead`/`PortWrite`/`PortReadWrite`, which can never have `const fn` implementaitons
2. `PageSize` which _always_ has a `const fn` implementation (as it's just  two associated consts)
The use of (1) can be eliminated by only constraining the `Port::read` method instead of the `Port::new` method. This is similar to what the standard library does for [Once::new](https://doc.rust-lang.org/beta/std/sync/struct.Once.html#method.new).

Remove Trait constraint for Port::new()

---

src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

This is useful for setting up the recursive page table mapping in the UEFI bootloader implementation. I also think that this method makes sense in general, e.g. for determining unused memory ranges for new mappings.

Provide functions for accessing the underlying L4 table for mapper types

---

src/lib.rs
src/structures/gdt.rs
src/structures/idt.rs

This requires making the push method const as well, which means we need
the `const_panic` feature (not too much of a risk as this feature is
failly well along).
I also moved the pointer calculation (for GDT and IDT) into their own
(currently private) methods. Eventually these methods can be public, but
that's only useful if they can be const, which would require a breaking change.
The caclulation for the GDT pointer was also updated to use:
```rust
self.next_free * size_of::<u64>() - 1
```
instead of
```rust
self.table.len() * size_of::<u64>() - 1
```

gdt: make add_entry const

---

.github/workflows/build.yml

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

CI: Use new environment files for modifying PATH

---

.github/workflows/build.yml

Sometimes Rust/Cargo or clippy introduce new (stylistic) warnings. We don't want to break our CI build over those. This PR changes or CI script to report these warning in the Github UI instead.

Don't deny warnings on CI

---

src/instructions/interrupts.rs

This commit deprecates `enable_interrupts_and_hlt` in favor of `enable_and_hlt`.
Fixes: #205

Rename `enable_interrupts_and_hlt` to `enable_and_hlt`

---

src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/recursive_page_table.rs

Extend `TranslateResult` returned by `MapperAllSizes::translate()` with
the page flags. This way, there is a method to get the flags for the
page of a `VirtAddr`.
_Edit(phil-opp)_: This is a **breaking change**.

feat(paging): Also return flags for `MapperAllSizes::translate()`

---

Changelog.md
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

This makes it possible to use the method with trait objects.
Resolves https://github.com/rust-osdev/acpi/issues/78

Relaxe `Sized` requirement for `FrameAllocator` in `Mapper::map_to`

---

Changelog.md
src/structures/paging/frame.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/page.rs

This fixes the clippy warnings we currently see on CI.
Since this changes the signature of public functions, this is a **breaking change**. However, I don't expect that much code is broken by this.

Use custom error types instead of `()`

---

Changelog.md
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/mod.rs

Implements the design proposed in https://github.com/rust-osdev/x86_64/pull/150#issuecomment-618342192 and fixes #152.
This is a **breaking change**: The `MapperAllSizes` trait no longer has any methods and is only kept for convenience. The `translate` and `translate_addr` methods are now available through a new `Translate` trait. The `TranslateResult` type was restructed to avoid repititions.

Restructure the `TranslateResult` type and create separate `Translate` trait

---

Changelog.md
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs

The new trait and method names better describe their purpose. Since the implementer must make sure that the returned pointer is valid and accessible, the trait is now unsafe to implement. Because of this requirement we also need to remove the generic implementation of this trait for closures.
(See https://github.com/rust-osdev/x86_64/pull/213 for an alternative, but unsuccessful, attempt).

Rename `PhysToVirt` trait to `PageTableFrameMapping`

---

Changelog.md
src/structures/gdt.rs
src/structures/idt.rs
src/structures/mod.rs

Makes it clear that segmentation is applied before paging.
Suggested in https://github.com/rust-osdev/x86_64/issues/193#issue-723081621.

Make `DescriptorTablePointer::base` a `VirtAddr`

---

Changelog.md
src/instructions/mod.rs

This makes it clear that the return type is a virtual address.﻿

Change return type of `read_rip` to `VirtAddr`

---

Changelog.md
src/instructions/port.rs
src/structures/port.rs

No longer needed after https://github.com/rust-osdev/x86_64/pull/188﻿

Remove `PortReadWrite` trait, which is no longer needed

---

src/instructions/mod.rs

When updating `x86_64` from 0.11.x to 0.12.x, I've gotten the following compilation error:
```
error: invalid instruction mnemonic 'xchgw'
--> /home/pierre/.cargo/registry/src/github.com-1ecc6299db9ec823/x86_64-0.12.3/src/instructions/mod.rs:51:15
|
51 |         asm!("xchgw bx, bx", options(nomem, nostack));
|               ^
|
note: instantiated into assembly here
--> <inline asm>:2:2
|
2  |     xchgw bx, bx
|     ^^^^^
```
According to [this Bochs-related page](https://wiki.osdev.org/Bochs#Magic_Breakpoint), the instruction is indeed just `xchg`, while `xchgw` is the weird AT&T syntax equivalent.
My code compiles with this change, but I haven't tested if the Bochs breakpoint actually works.

Fix bad conversion from llvm_asm! to asm!

---

src/structures/gdt.rs

Currently the API for `structures::GlobalDescriptorTable` feels like it requires you to either:
* use a [lazy_static][2] or
* use a `static mut` to store your GDT (which is a [bad idea][0])
That's because there's no way to actually form your GDT entries without using `add_entry` which takes `&mut self`... which seems contradictory that `load` requires the GDT to be `&'static self`!
you can get around this using a lazy_static of course but what if I want to use [once_cell][1] instead? there's no nice way of going about this... that's why this PR inroduces `load_unchecked` which is the same as `load` without the `'static` requirement and marked `unsafe` (of course.)
Also I noticed that sometimes you just know ahead of time what you want your GDT to be initialized with which lead me to add …

GDT: Add `load_unchecked`, `from_raw_slice`, and `as_raw_slice`.

---

Cargo.toml
Changelog.md

Releases a new patch version with https://github.com/rust-osdev/x86_64/pull/210 and https://github.com/rust-osdev/x86_64/pull/218.
cc @tomaka @mental32﻿

Release version 0.12.4

---

src/instructions/interrupts.rs
testing/Cargo.toml
testing/tests/interrupt_handling.rs

As this feature is stablized in the lastest nightly, no
feature flags need to be added.
Opening PR against the `next` branch as this is a breaking change.

Change software_interrupt to use min_const_generics

---

src/structures/idt.rs

This change is an alternative to #225:
- Moves the IDT entry's CS GDT selector to the options structure
- It also now uses SegmentSelector
- The `set_handler_fn` is now a proper generic function
- This is done by adding the `InterruptFn` trait
- Change behavior (and document) so `set_handler_fn` resets _all_ the
options (as opposed to some).

idt: Fixup Options structure and cleanup set_handler_fn

---

src/lib.rs

The feature `const_in_array_repeat_expressions` was removed on the latest Rust nightly, removing the feature fixes a hard compilation error on all crates that import `x86_64` in nightly.
```
error[E0557]: feature has been removed
--> /home/kernel/.cargo/registry/src/github.com-1ecc6299db9ec823/x86_64-0.13.1/src/lib.rs:9:43
|
9 | #![cfg_attr(feature = "const_fn", feature(const_in_array_repeat_expressions))]
|                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
|
= note: removed due to causing promotable bugs
error: aborting due to previous error
For more information about this error, try `rustc --explain E0557`.
error: could not compile `x86_64`
```

Fix build on latest nightly

---

src/addr.rs

Some minor improvements for debug traits for the address types:
* Adds `fmt::Binary`, `fmt::LowerHex`, `fmt::Octal`, `fmt::UpperHex` impls for `VirtAddr`
* Adds `fmt::Pointer` impls for `VirtAddr` and `PhysAddr`
* Use `fmt::Formatter::debug_tuple` in the `fmt::Debug` impls so formatting flags are respected

Implement more fmt traits for addr types

---

src/registers/mod.rs
src/registers/xcontrol.rs

Added support for the XCr0 register. Needed for enabling instruction extensions like SSE and AVX.
Missing the src/asm/asm.s counterpart because I can't / don't know how to test it.

Added XCR0 register

---

Cargo.toml
Changelog.md
src/structures/idt.rs
testing/tests/breakpoint_exception.rs
testing/tests/double_fault_stack_overflow.rs

It looks like the `x86-interrupt` calling convention passes the `InterruptStackFrame` by value, not by reference: https://github.com/rust-lang/rust/issues/40180#issuecomment-814270159. Apparently, by-ref worked as well before Rust upgraded to LLVM 12, but it no longer works on the latest nightlies. This pull request fixes the IDT to require a by-value stack frame parameter.
Since modifying the interrupt stack frame [now requires a volatile write](https://github.com/rust-lang/rust/issues/40180#issuecomment-817207466), this PR changes the return type of the `InterruptStackFrame::as_mut` function to a `Volatile<_>` reference.

Fixes for `x86-interrupt` calling convention

---

src/asm/asm.s
src/asm/mod.rs
src/instructions/tables.rs

Adds a function for getting the current IDT descriptor value. Motivation is largely that being able to get this value can be handy while debugging IDT-related faults.
I'm not 100% on whether the function is safe, but from the instructions description is seems safe to call, as at worst it can fault but it won't touch memory not at the location passed.

Add sidt support

---

src/instructions/port.rs

Using `#[derive(Debug, Clone, PartialEq, Eq)]` on the generic `Port<T>` types creates a bound on `T` which isn't necessary because the struct does not contain any values of type `T`. This isn't usually a problem because the only useful options for `T` (`u8`, `u16`, and `u32`) already implement these traits, but it can make it more annoying when working with other code that's generic over the port data type because you have to include these bounds. To fix this, I've manually implemented these traits without any bounds on `T`.

Looser trait bounds for Port types

---

src/lib.rs

Feature gate introduced in https://github.com/rust-lang/rust/pull/84310.
Unfortunately, unknown feature gates lead to errors so that this change errors on older nightlies. For this reason, I think we should at least wait until the common `rustfmt` component is fixed on nightly again because then everyone should be able to update. See https://rust-lang.github.io/rustup-components-history/ for component availability.
Fixes #252

Use new `const_fn_trait_bound` feature to fix build on latest nightly

---

Cargo.toml
Changelog.md
src/asm/asm.s
src/asm/mod.rs
src/instructions/interrupts.rs
src/instructions/mod.rs
src/instructions/port.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/instructions/tlb.rs
src/lib.rs
src/registers/control.rs
src/registers/model_specific.rs
src/registers/rflags.rs
src/registers/xcontrol.rs

See the individual commits for more information. 
Amongst other things, this PR adds `external_asm` implementations for some functions that were missing it and documents those functions which still require `inline_asm`
Example Docs:

Multiple improvements to the inline assembly code

---

Changelog.md
src/structures/idt.rs

This removes all `#[allow()]` statements except for:
- `#[allow(clippy::inconsistent_digit_grouping)]` for our page table math
- `#[allow(unused_unsafe)]` which will be removed when fixing #221 
See the individual commits for more information.

Minor lint fixes

---

Changelog.md
src/lib.rs
src/structures/gdt.rs
src/structures/paging/frame.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

Fixes #222
The following methods can be made `const` on stable:
- `GlobalDescriptorTable::from_raw_slice`
- `MappedFrame::{start_address, size}`
- `Page<Size4KiB>::p1_index`
The remaining functions still need `const_fn` because:
- Some GDT methods use `&mut self`
- The IDT uses function pointers as a type argument
- The PageSize marker trait is used all over
Comments were updated where appropriate.

Cleanup const_fn!

---

Changelog.md
src/instructions/port.rs
testing/src/lib.rs
testing/tests/port_read_write.rs

Changes the `Port` struct to use a type parameter and marker types for restricting read/write access instead of using entirely separate structs, reducing some code duplication and making it easier to be generic over access types.
I'm fairly confident this is a compatible change since the `A` parameter on `Port` defaults to `ReadWriteAccess` and `PortReadOnly` and `PortWriteOnly` still exist, albeit as type aliases now.
This conflicts with #247 a bit but it should be easy for me to deal with the conflicts.

Use marker types for Port read/write access

---

src/instructions/interrupts.rs

This pr replaces the `software_interrupt!` macro with a generic function.

replace software_interrupt! macro with generic function

---

testing/Cargo.toml
testing/tests/interrupt_handling.rs

So I just realized we already had some of the changes in #259 merged as part of #227.
This PR adds the rest of the testing code. CC: @Freax13 

software_interrupt: Add additional testing

---

src/structures/idt.rs

#226 got messed up (see https://github.com/rust-osdev/x86_64/pull/260#issuecomment-854461113)
This moves the `code_selector` to the `EntryOptions` structure.
While rebasing this, I also updated the `Debug` implementation to
actually print out useful information instead of just hex codes.
Now an `Entry` when using `{:#?}` looks like:
```rust
Entry {
handler_addr: 0x562341c25870,
options: EntryOptions {
code_selector: SegmentSelector {
index: 6,
rpl: Ring3,
},
stack_index: 5,
type: 0b1110,
privilege_level: Ring0,
present: true,
},
}
```
I left the type field as binary, as that's what the SDM does.

Resubmission of #226

---

src/structures/idt.rs

This makes the value easier to use and slightly improves the `Debug`
implementation. Also, change the `InterruptStackFrame` to
`#[repr(transparent)]`. It doesn't really matter but makes it clear that
`InterruptStackFrame` and `InterruptStackFrameValue` are ABI compatible.
Note that this now makes `InterruptStackFrameValue`s impossible to
construct, but that seems fine.

Use SegmentSelector in InterruptStackFrame

---

src/asm/asm.s
src/asm/mod.rs
src/instructions/segmentation.rs
src/registers/mod.rs
src/registers/model_specific.rs
src/structures/idt.rs
testing/src/gdt.rs

When working on #257 I noticed it might be a good idea to have a common trait for the FS and GS segments, to make their use in things like wrapper structs easier. In fact, it makes sense to have a (different) common trait for all of the segments.
This change introduces the following traits:
- `Segment`
- allows reading/writing the segment register
- implemented by `CS`, `DS`, `ES`, `SS`, `FS`, and `GS`
- `Segment64`
- allows reading/writing the segment base (using `VirtAddr` instead of `u64`)
- associated `const` for the `Msr`
- implemented by `FS` and `GS`
- this trait will eventually also have the `read_u64`/`write_u64` methods from #257
Now that the code has a similar structure for all segments, we can use macros to implement the traits.
Also, this change adds some additional …

Add common abstractions for x86 Segments 

---

src/asm/mod.rs

This ensures that the arguments to the external assembly functions are passed by RDI, RSI, RDX, RCX, etc.

chore: specify `sysv64` for the calling convention of the external assembly functions

---

src/structures/idt.rs
src/structures/mod.rs

This PR makes the `idt` module available for use in the stable Rust with the `instructions` feature.
Especially, this PR
- exposes `Entry::set_handler_addr` as an unsafe method. This is the only way for the users of this crate who build it with the stable Rust to set the addresses of the interrupt or exception handlers.
- defines the handler function types as `()` if the `abi_x86_interrupt` feature is not enabled. These types are only used with the `abi_x86_interrupt` feature.

feat(idt): make it available in the stable Rust

---

src/structures/gdt.rs

We use our poor-man's assert instead of trying to do math.
Fixes error pointed out by @toku-sa-n and @phil-opp here: https://github.com/rust-osdev/x86_64/pull/255#discussion_r632872856
Uses technique from: https://github.com/rust-osdev/x86_64/pull/264#discussion_r649024894

gdt: Fix off-by-one error in from_raw_slice()

---

src/addr.rs
src/lib.rs
src/structures/gdt.rs

We can't make the `{VirtAddr, PhysAddr}::{align_up, align_down, is_aligned}` methods const as they have a `U: Into<u64>` constraint.
We should consider removing this constraint for the next breaking change.

Make align_up and align_down const

---

src/structures/idt.rs

As documented here: https://wiki.osdev.org/Exceptions#Selector_Error_Code
Similar to the `PageFaultHandlerFunc` this adds a `SegmentNotPresentHandlerFunc`
The struct does need to be a repr(transparent) u64 otherwise a LLVM error occurs

Add a SelectorErrorCode to segment_not_present in IDT

---

src/registers/control.rs
src/registers/xcontrol.rs

Replacement for https://github.com/rust-osdev/x86_64/pull/272. @ethindp can you take a look?
- Remove the breaking changes
- Updated the documentation
- Fix the asserts when setting XCR0 
This PR adds some extras to the three control registers `CR0`, `CR4`, and `XCR0`. It also adds some checks for XCR0. (We could extend this to other registers as well.)
* CR0:
* Extension Type (ET, bit 4 of CR0)
* CR4:
* Key-Locker-Enable Bit (KL, bit 19 of CR4)
* Control-Flow Enforcement Technology (CET) enable (CET, bit 23 of CR4)
* Enable protection keys for supervisor-mode pages (PKS, bit 24 of CR4)
* XCR0:
* Enable XSAVE to manage the bound registers (BNDREG, bit 3 of XCR0)
* Enable XSAVE to manage the BCFGU and BNDSTATUS registers (BNDCSR, bit 4 of XCR0)
* Enable AVX-512 and allow XSAVE to manage …

Add flags for CR0, CR4 and XCR0, as well as extra checks for modification of XCR0

---

Cargo.toml
Changelog.md
src/instructions/segmentation.rs

Lets see if the CI works!
We will probably want to merge this instead of squashing it (to preserve git history)
Close #276

Release version to 0.14.4

---

src/registers/control.rs
src/registers/xcontrol.rs

Breaking changes from #272, part of #262 
NOTE: this was changed to only deprecate the new constant names, so it is no longer a breaking change.
@ethindp does this include all the breaking changes from your previous PR?

Rename XCr0 and CR4 flags

---

.github/workflows/build.yml
Cargo.toml
src/instructions/interrupts.rs
src/instructions/mod.rs
src/instructions/segmentation.rs
src/lib.rs
src/registers/control.rs
src/registers/model_specific.rs

The documentation can also be built locally using `cargo doc --open`. Doc links should be working there as well.

Use `#[cfg(doc)]` instead of docs.rs-specific cfg flag

---

src/structures/paging/mapper/mod.rs

It looks like there is no way to create an instance of these types.
Fixes: #295

feat(mapper): expose `MapperFlush(All)?::new`

---

src/structures/gdt.rs

This is a small change to the documentation of the `GDT::load` and `GDT::load_unsafe` methods to point the following deprecated methods at their new replacements:
- [load_ss](https://docs.rs/x86_64/0.14.4/x86_64/instructions/segmentation/fn.load_ss.html#) -> [SS::set_reg](https://docs.rs/x86_64/0.14.4/x86_64/instructions/segmentation/struct.SS.html#method.set_reg)
- [set_cs](https://docs.rs/x86_64/0.14.4/x86_64/instructions/segmentation/fn.set_cs.html) -> [CS::set_reg](https://docs.rs/x86_64/0.14.4/x86_64/instructions/segmentation/struct.CS.html#method.set_reg)

docs: Update segment register references in GDT::load* method to non-deprecated methods

---

src/structures/idt.rs

docs(idt): remove a panic note

---

src/structures/idt.rs

These embeddable types can be used to parse the various errors.
cc @haraldh

Add exception vector type

---

Cargo.toml
Changelog.md

Updates the changelog to include the recent changes and bumps the version to 0.14.5.
(The CI will take care of creating the git tag and pushing to crates.io after merging.)
This releases the following PRs: #275, #287, #296, #300, #301, #302, #264, #303, #306

Release version 0.14.5

---

.github/workflows/build.yml
src/instructions/segmentation.rs
src/registers/control.rs
src/registers/mod.rs
src/registers/model_specific.rs
src/registers/segmentation.rs
src/structures/gdt.rs

The segment types themselves and the related traits do not require the `instructions` feature, so I think that it makes sense to move them to the top-level `registers` module. The `instructions::segmentation` module still re-exports all the types, so this change should not break any code. I also moved the `SegmentSelector` type from the `gdt` module to the new module since it's more related to the segment registers than to the GDT.
This should fix `cargo doc` errors reported in #307 since the segment types are now available even without the `instructions` feature. Some special handling was necessary for the `GsBase` and `KernelGsBase` types: They now use a `#[cfg_attr(feature = "instructions", doc = "...")]` to append the link to the `swap` method only when it is available.
To ensure that …

Move segment types into a new `registers::segmentation` module

---

src/structures/idt.rs

Derive `Copy` for `InterruptStackFrameValue` or otherwise
```
error[E0277]: the trait bound `InterruptStackFrameValue: core::marker::Copy` is not satisfied
```
Signed-off-by: Harald Hoyer <harald@profian.com>

fix: enable manipulation of `InterruptStackFrame`

---

src/registers/model_specific.rs

This pr makes `Star::write` return `Result<(), InvalidStarSegmentSelectors>` instead of `Result<(), &'static str>`. 

add `InvalidStarSegmentSelectors`

---

src/instructions/tlb.rs

This pr makes `Pcid::new` return `Result<Pcid, PcidTooBig>` instead of `Result<Pcid, &'static str>`. 

add `PcidTooBig` error

---

src/structures/paging/frame.rs

This PR removes double alignment check - proper alignment to `S::Size` is asserted by this condition:
```rust
if !address.is_aligned(S::SIZE) {
return Err(AddressNotAligned);
}
```

Remove redundant alignment check

---

src/structures/idt.rs

This pr adds the `set_general_handler!` macro to set a general handler in an idt using only macro_rules. It's an alternative to #168 and all of the tests are taken from it.
As already mentioned in https://github.com/rust-osdev/x86_64/issues/167#issuecomment-654946675 there are no loops in macro_rules macros, so I used recursion instead:
https://github.com/Freax13/x86_64/blob/8252697d6ef5b567ff6a8110656f9a50e00df051/src/structures/idt.rs#L936-L956
I believe this to be a relatively short and concise solution. The only major drawback with this approach is that we can't do the range checks a compile time, so the macro always has to expand to setting all 256 interrupts even if some of those will be skipped at runtime. The upside of this approach is that the range doesn't necessarily need to be …

add set_general_handler macro

---

src/addr.rs
src/instructions/tlb.rs
src/lib.rs
src/registers/segmentation.rs
src/structures/idt.rs
src/structures/paging/frame.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

Rust's api guidelines recommend [eagerly implementing common traits](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits). There has already been some discussion #43 whether implementing all traits is always the best idea.
This pr add derives for `Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash` to some number and range types. These types are newtypes around integers and don't have any implementation details to hide, so adding these derives should be unobjectionable. This pr also adds the same derives to some enum types. 
Initially I only wanted to add theses derives to `Pcid`, but I noticed that other types were also missing some of them and decided to add them as well.

Derive common traits for number, range and enum types

---

src/lib.rs

CI is failing because yesterdays nightly release broke const operands in asm (see https://github.com/rust-lang/rust/pull/90348). They now require `#![feature(asm_const)]`. Luckily we only use those on the `next` branch, so the master branch and all releases on crates.io should be fine.
This pr activates the `asm_const` feature when `inline_asm` is enabled.

activate `feature(abi_x86_interrupt)`

---

src/structures/idt.rs

This pr changes the `Idx` type of `InterruptDescriptorTable`'s `Index` implementation from `usize` to `u8` as discussed in https://github.com/rust-osdev/x86_64/pull/285#discussion_r744148763. `u8` more accurately represents the index for an `InterruptDescriptorTable` which always has exactly 256 entries. This change also eliminates some out of bounds panics that were possible with `usize`.
There was some discussion following https://github.com/rust-osdev/x86_64/pull/95#issuecomment-557496537 on whether it would be possible to use [`SliceIndex`](https://doc.rust-lang.org/std/slice/trait.SliceIndex.html) now or in the future. Following this pr this is no longer useful because `SliceIndex` is based around only `usize` not `u8`. Since using `SliceIndex` is now out of question, there shouldn't …

implement `Index<u8>` for IDT instead of `Index<usize>`

---

Cargo.toml
src/registers/rflags.rs
src/structures/idt.rs

https://github.com/rust-osdev/x86_64/issues/262 mentions that we should use correct types for `InterruptStackFrameValue`. This pr changes `cpu_flags` from u64 to `RFlags`, adds `#[repr(transparent)]` to `RFlags` and upgrades the `bitflags` dependency to the latest version. This last change is needed because "unknown" bits weren't officially supported until version `1.2.0`, starting with `1.2.0` crate authors must define what bit representations are valid for a type.

change `cpu_flags`'s type to `RFlags`

---

src/structures/idt.rs

Signed-off-by: Harald Hoyer <harald@profian.com>

fix(idt): fix panic messages for `index` and #VC

---

src/instructions/tables.rs
src/lib.rs
src/structures/gdt.rs
testing/src/gdt.rs

`ltr` atomically writes to memory when it changes the referenced tss entry's type to `Busy 64-bit TSS`. This means that the inline assembly in `load_tss` should not have the `nomem` option and that the `table` field in `GlobalDescriptorTable` must use a type that is interiorly mutable.
Unfortunately this is a breaking change because I changed the type of `GlobalDescriptorTable::table` to `[AtomicU64; 8]` and  `GlobalDescriptorTable::as_raw_slice` exposes this field to the public api. Returning `&[u64]` wouldn't be safe anyways because `[u64]` isn't interioly mutable.
Technically this means that the old code was probably UB, but my guess is it's unlikely that anyone was actually affected by this.
#322 initially brought up that `load_tss` changes the GDT. This pr does not fix #322, but #322 …

fix `load_tss` and `GlobalDescriptorTable`

---

src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

This pr adds immutable getters for the level 4 page tables. It also appends the `_mut` suffix to the already existing getters.
Related to #325

add an immutable getter for the level 4 page table

---

src/addr.rs
src/lib.rs
src/structures/gdt.rs

Rust 1.57 was just released and ["`panic!` in const contexts"](https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#panic-in-const-contexts) has finally been stabilized :tada:. This pr removes the hacky `const_assert!` macro that we previously used to conditionally abort the compilation in const contexts.

remove `const_assert!` in favor of std's `assert!`

---

.github/workflows/build.yml
src/instructions/interrupts.rs
src/instructions/mod.rs
src/instructions/port.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/instructions/tlb.rs
src/registers/control.rs
src/registers/model_specific.rs
src/registers/rflags.rs
src/registers/xcontrol.rs

`asm!` is excluded from Prelude.

fix: build error on the latest nightly

---

.github/workflows/build.yml

We should not make this test part of the manditory test suite because the bootloader crate depends on x86_64 itself. Thus, some breaking changes require a two-phase update.

Move bootloader integration test to separate CI job

---

src/instructions/port.rs
src/instructions/segmentation.rs
src/instructions/tables.rs
src/instructions/tlb.rs
src/lib.rs
src/registers/control.rs
src/registers/model_specific.rs
src/registers/rflags.rs
src/registers/xcontrol.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

This pr enables the `unsafe_block_in_unsafe_fn` lint.
Closes #221

enable `unsafe_block_in_unsafe_fn` lint

---

Cargo.toml
Changelog.md

Contains the following changes:
- fix: build error on the latest nightly ([#329](https://github.com/rust-osdev/x86_64/pull/329))
- add `set_general_handler` macro ([#285](https://github.com/rust-osdev/x86_64/pull/285))
- Derive common traits for number, range and enum types ([#315](https://github.com/rust-osdev/x86_64/pull/315))
- Add the VMM Communication Exception (`#VC`) to the `InterruptDescriptorTable` ([#313](https://github.com/rust-osdev/x86_64/pull/313))
- fix: enable manipulation of `InterruptStackFrame` ([#312](https://github.com/rust-osdev/x86_64/pull/312))
- fix docs for `page_table_index` ([#318](https://github.com/rust-osdev/x86_64/pull/318))
- Remove redundant alignment check ([#314](https://github.com/rust-osdev/x86_64/pull/314))
- fix(idt): fix panic messages for `index` …

Release version 0.14.7

---

src/registers/control.rs

This pr adds `Cr2::read_raw`.
Closes #332

add `Cr2::read_raw`

---

src/asm/asm.s
src/asm/mod.rs
src/registers/mod.rs
src/registers/mxcsr.rs

Add MxCsr register derived from MxCsr type in enarx/xsave.
Provide two unit tests:
- mxcsr_default(): Check that the constant matches the value read from
the CPU when the process has not yet written anything else to it.
- mxcsr_write(): Check that the write operation does not corrupt values.
Closes: https://github.com/enarx/enarx/issues/1000
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@iki.fi>

registers: MXCSR

---

src/addr.rs

This pr makes the fields of the `VirtAddrNotValid` and `PhysAddrNotValid` error types public.
This was suggested by @phil-opp: https://github.com/rust-osdev/x86_64/pull/335#discussion_r785689623.

make fields public

---

src/registers/control.rs

This pr adds `Cr2::read_raw` and makes `Cr2::read` return a result.
Closes #332

make `Cr2::read` return a result

---

.github/workflows/build.yml
Cargo.toml
README.md

This pr removes the deprecated `external_asm` and `inline_asm` features for the next breaking release.
This is a followup pr for https://github.com/rust-osdev/x86_64/pull/343#pullrequestreview-893417513.

remove `external_asm` and `inline_asm` features

---

src/addr.rs

Before it contained just the invalid higher bits. We made the internal fields public in #340, but fortunately we didn't release this change yet, so this fix is still non-breaking.

Fix: `VirtAddrNotValid` and `PhysAddrNotValid` should contain the whole address

---

Cargo.toml
src/addr.rs
src/lib.rs
src/structures/paging/page.rs

This pr implements `core::iter::Step` for `VirtAddr` and `Page` and adds corresponding unit tests. 
This implementation jumps the gap between `0x7fff_ffff_ffff` and `0xffff_8000_0000_0000` as discussed in https://github.com/rust-osdev/x86_64/issues/293#issuecomment-903260820. 
The `Step` trait is still unstable, so the implementation is put behind a new feature flag `step_trait`. This flag is enabled by the `nightly` feature flag. 
Part of #212

implement `core::iter::Step` for `VirtAddr` and `Page`

---

src/structures/paging/page.rs

This PR is to implement the solution suggested by @phil-opp and @Freax13 in #346. Please let me know your thoughts.
One thing that maybe could use doing still: I wanted to add a test case to check this, but it looks like the testing code is largely copied from blog_os and maybe isn't used? I admit I am _really_ not familiar with unit testing so I could use some help on writing a test if that is something you guys would like to see.

Fixed overflow bug in PageRangeInclusive

---

src/registers/model_specific.rs

This embedded to some of SGX structures (at least SECS and REPORT), so that's I need to bring some support to x86_64 crate. Does not cover fields TRACKER but EB_LEG_BITMAP_BASE but:
- They are not part of the settable flags.
- They need to be encoded and decoded separately, i.e. in all cases need their own accessors
Actually SGX structures and encl* need only UCetFlags but it would have been crippled just to implement that structure without context.

User CET Register

---

src/lib.rs
src/structures/idt.rs
src/structures/paging/frame.rs
src/structures/paging/page.rs

Both `const_fn_fn_ptr_basics` and `const_fn_trait_bound` were stabilized
in Rust relese 1.61. We can't immediately remove the `const_fn!` quite
yet. 1.61 is not yet on stable, and even it were, removing them would
increase our MSRV to 1.61 (which we may or may not want to do in a patch
release).
See also: https://github.com/rust-osdev/x86_64/issues/262#issuecomment-1077340045

const_fn: Remove stabilized features

---

.github/workflows/build.yml
Cargo.toml
README.md
src/addr.rs
src/lib.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/paging/frame.rs
src/structures/paging/page.rs

The first two commit cleanup some out-of-date documentation
The third commit uses the `rustversion` create to make the methods from #352 `const` if the user is on a new enough compiler version.
The fourth commit removes the `const_fn!` macro, and uses `rustversion` to just enable the `GlobalDescriptorTable` const methods if the `const_fn` feature is selected.
In theory, we could also remove/deprecate the `const_fn` feature, and just have the GDT methods be const unconditionally if the compiled on nightly. That's a more complicated question, so I'll leave it for a follow up PR.

Use rustversion and remove const_fn!

---

src/structures/idt.rs

This is a very minor change that's both harmless and useful for various purposes in an OS.
PR submitted at the request of @phil-opp ([see here](https://github.com/theseus-os/Theseus/pull/499#issuecomment-1077368004))
Note that we could gate the function (or just its `pub`-ness) behind `cfg(feature = "instructions")` for consistency, but then we'd need to change the implementation of `Debug` for `Entry`. Seems best to leave it as is.
We could also construct a `VirtAddr` from the return value and return that instead, but personally I believe that adds unnecessary complexity. I also think some of this crate's other functions assume `VirtAddr`s in a lot of high-level wrapper functions where the value doesn't necessarily represent a virtual address (but that's a matter for a separate issue), …

Make `Entry::handler_addr()` a public method

---

src/instructions/tables.rs

As pointed out in #323, `ltr` writes memory, as it modifies the corresponding TSS `Descriptor` in the GDT. Because of this, setting `nomem` is inaccurate.

Don't set nomem in load_tss

---

src/structures/tss.rs

Fixes #195.
To make the IOPB invalid we set it to `1` more than the TSS segment limit. This is [what linux does](https://github.com/torvalds/linux/blob/eaa54b1458ca84092e513d554dd6d234245e6bef/arch/x86/include/asm/processor.h#L370). 

tss: Initialize iopb to be empty instead of zero

---

.github/workflows/build.yml
Cargo.toml
README.md
src/structures/idt.rs
src/structures/paging/mapper/mod.rs

This change updates our `README` to note what our Minimum Supported Rust Version (MSRV) is for each feature configuration. It also uses the [`rust-version` cargo feature](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) to make this information consumable by cargo.
Our MSRVs are:
- `not(instructions)` and `not(nightly)` - Rust 1.57
- `instructions` and `not(nightly)` - Rust 1.59
- `nightly` - Rust Nightly (sufficiently recent)
I also updated some of our tests so that things would build/test on stable without errors or warnings. Finally, I updated the CI to actually test our MSRV (by moving some of our tests to a different "stable" job).

Update Docs and CI to note MSRV

---

src/structures/gdt.rs

This uses a const generic `MAX` parameter to specify the length. This is arguably a breaking change as it bumps the MSRV to 1.59 though its use of default const generics. It also can make some function call require additional type annotations:
```rust
// Before
let gdt = GlobalDescriptorTable::from_raw_slice(slice);
// After
let gdt = GlobalDescriptorTable::<8>::from_raw_slice(slice);
```
Fixes #333 

Allow the GDT to be of any length

---

src/instructions/interrupts.rs

Given that const generics are stable but const values in `asm!` are not,
having a macro in addition to a generic function isn't really useful.
See https://github.com/rust-osdev/x86_64/pull/344#discussion_r835898335

Remove software_interrupt! macro

---

src/addr.rs
testing/src/gdt.rs

This removes `Add`/`AddAssign`/`Sub`/`SubAssign` with `usize` from
`VirtAddr` and `PhysAddr` (which are always 64-bit, even on 32-bit
platforms). This makes it possible to write code like:
```rust
let addr1 = PhysAddr::new(0x52);
let addr2 = addr1 + 3;
```
without getting a "multiple `impl`s" compiler error.
This is essentially the breaking change mentioned in
https://github.com/rust-osdev/x86_64/issues/293#issuecomment-901804330

Remove usize trait impls

---

src/structures/gdt.rs

This is a minor, non-breaking change.
When pushing a `SystemSegment` the GDT has to have two entries free. Rather than pushing part of the `SystemSegment` and _then_ panicking, we can panic before we even modify the GDT, and give a better error message. This new behavior also seems  less surprising, as normally if a mutation operation panics, the structure isn't modified.
I also renamed the `next_free` private member to `len` (with these changes it makes the code more readable). I also added some tests to make sure we are correctly handling the `add_entry` command.

gdt: Improve panic message when SystemSegment is pushed

---

src/structures/gdt.rs

The GDT can have a maxium length of 2^16 bytes, and must contain at
least one null descriptor. As `MAX` counts the number of `u64` entries,
we must have `0 < MAX <= 2^13`.
Unfortunely, we cannot do this check with a `where` clause, as
`feature(generic_const_expers)` is not yet stable. However, we can do
this check with an `assert!` in `GlobalDescriptorTable::empty()`, which
is a `const fn`.
Pointed out by @Freax13 in
https://github.com/rust-osdev/x86_64/pull/360#discussion_r836788703

gdt: Check that MAX is in range

---

src/structures/mod.rs
src/structures/tss.rs

While both TaskStateSegment and DescriptorTablePointer can't have their
normal C alignment due to their definition. However, this doesn't mean
their alignment has to be `1`.
This PR sets their alignment to be the max possible while still
preserving their ABI definied structure. I added some tests to make sure
there is not a regression.
This can also result in more efficient code generation on platofrms
without unalgined loads. https://rust.godbolt.org/z/EPbbMxeq1

Increase alginment for packed structures

---

src/addr.rs

Specifically:
- VirtAddr::as_ptr()
- VirtAddr::as_mut_ptr()
- PhysAddr::new()
- PhysAddr::try_new()

Make more VirtAddr and PhysAddr methods const

---

src/instructions/tables.rs
src/structures/gdt.rs

Hopefully, this help address confusion like that seen in:
https://github.com/rust-osdev/x86_64/issues/322

tss: Update documentation

---

src/addr.rs
src/instructions/interrupts.rs
src/structures/idt.rs

The first commit removes our `*const T -> VirtAddr` conversion on 32-bit platforms. Per the comment, it's "only here for backwards compatibility". Should we go even further and remove the conversions on all non-`x86_64` platforms?
The second commit makes it so `new` and `try_new` fail on non-canonical addresses. Fixes #299 
The third commit make `new` and `try_new` const. Other `VirtAddr`/`PhysAddr` methods are made const in #369 (which will be pulled back into this branch when its merged).

VirtAddr improvements

---

src/registers/segmentation.rs
src/structures/gdt.rs

This may be useful when used as a segment selector to load a non-existent segment into the data register.
e.g.
```
DS::set_reg(gdt.null_segment_selector())
```

 Provide null segment selector as associated constant on SegmentSelector

---

src/addr.rs

This pr fixes `VirtAddr::align_up` and`VirtAddr::align_down`. Previously those functions returned non-canonical addresses when aligning addresses near the address space gap. Two tests were added to test such cases.
This pr also fixes`PhysAddr::align_up` by adding a check to make sure the address is not too big.

fix align functions

---

src/instructions/segmentation.rs

We no longer use the symbols for the external assembly, so we can
simplify the macros.

Cleanup Segment macros

---

src/registers/segmentation.rs

Unlike the comment suggests, more descriptor fields than mentioned in the comment are recognized by the CPU.

Correct wrong comment.

---

src/lib.rs
src/structures/gdt.rs
testing/src/gdt.rs

The current documentation for the GDT often confuses entries and `Descriptor`s.
For example, adding a new `Descriptor` uses a method confusingly named
`add_entry`.
An entry is a raw 64-bit value that is indexed by a segment selector.
The `MAX` length of the GDT is a number of _entries_, not `Descriptor`s.
To fix this confusion, this PR makes the following changes:
- Adds a transparent `u64` newtype called `Entry`.
- Updates the `GlobalDescriptorTable` documentation to correctly use
`Entry` or `Descriptor` where appropriate.
- Renames the `add_entry` to `append`.
- This better expresses that this method might add multiple entries.
- Renames `from_raw_slice` to `from_raw_entries`
- As @Freax13 provided out, if we add some checks, this method can be safe.
- Renames `as_raw_slice` to …

Add structures::gdt::Entry type

---

src/lib.rs
src/structures/gdt.rs
testing/src/gdt.rs

Depends on #380 
In #322 it was pointed out that calling `load_tss` would modify the GDT entry for the TSS (to mark it as busy). This meant our GDT required some sort of interior mutability if we wanted to use it in a `static`  context. #323 solved this problem by requiring `&mut` to call `load` and `load_unsafe`, thus ensuring that the GDT would be mutable after it was loaded. It also introduced `SingleUseCell` to make such manipulations more ergonomic.
This PR takes a different approach. The idea is basically the initial version of #323 using `AtomicU64`. The main difference is that:
- We can use the `Entry` type from #380 to make the code cleaner.
- We only need to use `AtomicU64` if it's possible for code to call `load` and `load_tss`, so we can gate this on `#[cfg(feature = …

Allow GDT to be loaded with shared reference

---

README.md
src/structures/paging/frame_alloc.rs

First commit adds a Safety comment to `FrameAllocator`, fixing a clippy warning.
Second commit adds links to other useful OS crates. Fixes #372

Update comment and docs

---

src/registers/debug.rs
src/registers/mod.rs

Fixes https://github.com/rust-osdev/x86_64/issues/284.
This adds `registers::debug`.
* `Dr0`-`Dr3` implement `DebugAddressRegister`.
* `Dr6Flags` can be read from `Dr6`.
For `Dr7` I added `Dr7Value` which contain `Dr7Flags` but has functions to modify the bits corresponding to the condition and size fields. Via `Dr7Value::flags_mut`, you can modify flags in place.

Add registers::debug

---

src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/offset_page_table.rs

This pr adds two getters `MappedPageTable::page_table_frame_mapping` and `OffsetPageTable::offset`. It also fixes the doc comment for `MappedPageTable::new`.

add getters for the page table frame mapping

---

src/structures/paging/page.rs

When we construct the address from the page table indices, we don't make the address canonical. This was fine in the previous versions where we automatically corrected this in `VirtAddr::new`, but that's no longer the case. Instead we can use `VirtAddr::new_truncate`.

fix `Page::from_page_table_indices`

---

src/structures/paging/page_table.rs

I don't know if this is really useful, but for me, it is (or my code just
sucks) and I think that having this function doesn't hurt but I can understand
if you think that it's useless.

Adding next_higher_level to PageLevelIndex

---

src/structures/paging/page_table.rs

I think that this would be nice to have instead of writing
`page_table.iter().all(|entry| entry.is_unused())` all the time.

Adding `is_empty` to PageTable

---

Cargo.toml
src/registers/control.rs
src/registers/debug.rs
src/registers/model_specific.rs
src/registers/rflags.rs
src/registers/xcontrol.rs

Now that the representation is fixed, these types can be embedded into other structures such as AMD's `VMCB` and `VMSA` or Intel's `ATTRIBUTES` (SGX).

set repr to transparent for various types

---

Cargo.toml
src/lib.rs

We used this unstable feature in the past for annotating nightly-only macros that require inline assembly: https://github.com/rust-osdev/x86_64/commit/17ca2b07cdee30daf9ea4c5c7d271f2cb998b00b. Now that inline assembly is stable, we don't use that feature anymore, so I think we can remove it.

Remove unused `doc_cfg` feature

---

Cargo.toml
src/lib.rs

This flag includes `#[cfg]` bounds in the generated documentation.
For example, the docs for the `x86_64::structures::paging::mapper` module now look like this:
We see that `OffsetPageTable` is now annotated with `64-bit` because the module has `#![cfg(target_pointer_width = "64")]`. Similarly, the `RecursivePageTable` struct is now annotated with `instructions` because it is `#[cfg(feature = "instructions")]`.

Enable `doc_auto_cfg` on `docs.rs` builds

---

.github/workflows/build.yml

For some reason cargo-xtest cannot be found on Windows if the shell is not set to bash. This used to work and regressed about two weeks ago for not immediately obvious reason. Considering that there is no big downside to running xtest with the bash shell, we'll just use that for now.
See https://github.com/rust-osdev/x86_64/actions/runs/4350740158 as an example of a run that fails because cargo-xtest cannot be found.

run xtest bash shell

---

src/instructions/port.rs
src/lib.rs
src/structures/paging/frame.rs
src/structures/paging/page.rs

Users should never implement this trait themselves. This also allows us to add more supertraits to `PageSize` and `NotGiantPageSize` without introducing a major breaking change.
This is a breaking change (though I really hope users haven't been doing this previously).

seal off the `PageSize` trait

---

src/lib.rs
src/structures/gdt.rs

This requires making `PrivilegeLevel::from_u16` const. That, in turn, requires making the panic message slightly less informative.
Note that this is also a functional change when building a GDT. Before, if you had a User/System Segment, the RPL would always be 0, unless it was a User Segment with a DPL of 3, in which case the RPL would be 3. Now the RPL will consistently match the DPL. This seems like the more intuitive approach. However, I doubt it makes much of a difference in practice (as the RPL mechanism is sort of useless to begin with).
If this functional change is an issue, I can add in code (and documentation) to explicitly define the DPL -> RPL mapping.

Add Descriptor::dpl const method and use it in GDT construction

---

.github/workflows/build.yml
.github/workflows/release.yml

Closes #411 
- set permission to build.yml to contents read. Success run example: https://github.com/joycebrum/x86_64/actions/runs/4451339527
- set top level permission of release.yml to contents: read and grant contents: write on the job level. Considering the parmission to read on crates, I could not test it completely (although it had run with success on my fork). But considering that the GITHUB_TOKEN would basically be used to the POST on refs, the contents: write is enough.
Thanks and let me know if I missed anything.

Set permissions to github workflows

---

src/registers/model_specific.rs

I did a little goof and used the wrong numbers in my own project while using this and instead of a more relevant error I got one for overflow from subtraction and had to look at the source code, so this fixes that.

Change Star::write() to use checked subtractions

---

Cargo.toml
src/registers/control.rs
src/registers/debug.rs
src/registers/model_specific.rs
src/registers/mxcsr.rs
src/registers/rflags.rs
src/registers/xcontrol.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/paging/page_table.rs

All of the types that use `bitflags!` have `#[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy)]` on them to preserve backwards compatability as recommended by the bitflags changelog.

Bump bitflags to 2.3.2

---

src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/page_table.rs

This pr adds changes the iterator returned by `PageTable::iter{_mut}` to a custom iterator that avoids calculating the end pointer of the page table. It also adds a warning against using recursive index 511.
Closes #424

add workaround for recursive page tables with recursive index 511

---

src/structures/paging/page_table.rs

The off-by-one error was confusing at first, wasn't sure if there was a 1-indexed behavior with page tables that I wasn't aware of.

Fix off-by-one in documentation

---

src/structures/gdt.rs

See #423, specifically [this comment](https://github.com/rust-osdev/x86_64/issues/423#issuecomment-1606054113), for background.

Add `Descriptor::tss_segment_unchecked`

---

src/instructions/segmentation.rs

Continuation of https://github.com/rust-osdev/x86_64/issues/125 I suppose.

Add `inline` attribute to segment functions

---

src/structures/idt.rs

I've added the `iretq` function that can be used to transition from a higher privilege level to a lower privilege level. This can be useful when implementing multitasking for example.

Add the `iretq` function to the `InterruptStackFrameValue` struct.

---

src/instructions/interrupts.rs

This actually bit me on AArch64, but this should apply to x86-64 as well:
Without this PR, the compiler may reorder memory accesses over these `asm!` calls. While `interrupts::enable` and `interrupts::disable` don't make claims about synchronizations, the docs strongly imply synchronization of the calling thread with _itself_.
Essentially, without compiler fences, code after `interrupts::disable` may still execute while interrupts are enabled. Conversely, code before `interrupts::enable` may only execute after interrupts have been enabled. This also translates to `without_interrupts`: code inside the closure may actually execute _with_ interrupts.
This bug may require very specific conditions to show up. In my case ([the Hermit kernel](https://github.com/hermit-os/kernel)), some …

fix(interrupts): add compiler fences to enable and disable

---

src/addr.rs
src/instructions/tlb.rs
src/structures/paging/page.rs

`flush_broadcast` can be used to broadcast TLB flushes to all CPU cores and `tlbsync` can be used to wait for those flushes to be done.

add `flush_broadcast` and `tlbsync` functions

---

Changelog.md
src/structures/idt.rs

Add HandlerFuncType trait

---

src/instructions/interrupts.rs

Follow up on https://github.com/rust-osdev/x86_64/pull/436.
I am sorry to open this discussion again, but the previous PR is not sufficient to prevent unexpected behavior.
Compiler fences only synchronize with atomic instructions. When creating a thread-local critical section, we need to prevent reordering of any reads and writes across interrupt toggles, not just atomic ones. To achieve this, we omit `nomem` from `asm!`. Since then, the assembly might potentially perform synchronizing operations such as acquiring or releasing a lock, the compiler won't move any reads and writes through these assembly blocks.
See https://github.com/mkroening/interrupt-ref-cell/issues/5#issuecomment-1753047784.
As an unrelated optimization, I also added `preserves_flags` here, since `IF` from `EFLAGS` must …

fix(interrupts): replace compiler fences with potentially-synchronizing assembly

---

src/addr.rs

Normally it's easily possible to create a `VirtAddr` via a reference using the `from_ptr` function. However this doesn't work with slices, because they are unsized. 
My first idea was to simply modify `from_ptr<T>` to `from_ptr<T: Sized?>`, however that does not work because slices are wide pointers and therefor have to be cast into a narrow pointer first.

add from_slice to VirtAddr

---

.github/workflows/build.yml

Looks like the semver checks work on stable even though we're using some unstable features.
This fixes the failing semver checks CI job.

CI: Run `semver-checks` using stable Rust

---

src/registers/control.rs

We already expose `Cr3::read_raw`, so we might as well expose the write variant.

expose `Cr3::write_raw`

---

src/registers/control.rs
src/registers/debug.rs
src/registers/model_specific.rs
src/registers/mxcsr.rs
src/registers/rflags.rs
src/registers/xcontrol.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/paging/page_table.rs

See https://github.com/rust-osdev/x86_64/pull/446#issuecomment-1890977003.

remove deprecated from_bits_unchecked functions

---

src/structures/idt.rs

Based on https://github.com/rust-osdev/x86_64/pull/446#discussion_r1451751783.

make `HandlerFuncType` unsafe

---

Changelog.md
src/structures/idt.rs

- Update docs to clarify new defaults for `set_handler_fn`
- Use the doc comment introduced in https://github.com/rust-osdev/x86_64/pull/226.
- List new IDT defaults as breaking change in changelog

Update docs to clarify new `set_handler_fn` behavior

---

testing/x86_64-bare-metal.json

Fix data layout in custom target used for testing

---

src/structures/paging/page.rs

The new code behaves exactly the same as the old code, but can be much better optimized by LLVM. In particular the bounds checks previously implied through `set_bits` and `VirtAddr::new` can now be elided. This also increases the chances of these functions being inlined.
The generated assembly for the old implementation looks like this:
```asm
x86_64::structures::paging::page::Page::from_page_table_indices:
push    rax
movzx   edi, di
cmp     edi, 512
jae     .LBB48_8
movzx   esi, si
cmp     esi, 512
jae     .LBB48_8
movzx   edx, dx
cmp     edx, 512
jae     .LBB48_8
movzx   eax, cx
cmp     eax, 512
jae     .LBB48_8
mov     rcx, rdi
shl     rcx, 39
shl     rsi, 30
or      rsi, rcx
shl     rdx, 21
shl     rax, 12
or      rax, rdx
or      rax, rsi
shr     edi, 8
je      .LBB48_7
cmp     edi, …
```

optimize from_page_table_indices

---

.github/workflows/build.yml
Cargo.toml
Changelog.md
src/structures/paging/page.rs
testing/x86_64-bare-metal.json

Following this PR, we can then immediately open up another PR merging `next` into `master`. There shouldn't be any conflicts because we recently merged `master` into `next`.

mark as 0.15 as beta release

---

Cargo.toml
Changelog.md

This will be the last non-breaking release before v0.15
Updates the Changelog to include all changes (except for those related to testing/CI).

Release v0.14.12

---

scripts/ci-release.py

This switches to using the sparse index as reccomended by: https://crates.io/data-access#api
Once merged, this should automatically release v0.14.12 (see #457).

Fix release script

---

testing/x86_64-bare-metal.json

Should fix the "Bootloader Integration Test" job on CI.

Update data layout of test target for LLVM 18

---

.github/workflows/build.yml
src/addr.rs

This PR optimizes the `Step` methods for `VirtAddr`.
Some of these optimizations were already present in the [PR](https://github.com/rust-osdev/x86_64/pull/342) that introduced the `Step` implementation but were removed over [safety concerns](https://github.com/rust-osdev/x86_64/pull/342#issuecomment-1055278236). To address these concerns, this PR also adds some [kani](https://github.com/model-checking/kani) proof harnesses to prove the correctness of the implementations. The proof harnesses are run in CI.

optimize `Step` impl for `VirtAddr`

---

src/addr.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

This PR contains various miscellaneous improvements. I recognize that some of these are independent of one another, but given the small over-all size I decided to open just one PR. Let me know if you'd like multiple smaller PRs instead.

miscellaneous improvements

---

src/structures/paging/mapper/mod.rs

Added as asked by phil opp, see #461

doc: added help on update_flags to get flags

---

src/structures/idt.rs

fix https://github.com/rust-osdev/x86_64/issues/466

Feat: add constructor for `InterruptStackFrameValue`

---

src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

Starting with 0.15, the addition operator will no longer implicitly jump the gap in the address space. Instead, we can use Step::forward.
Fixes #468

properly jump the address gap in CleanUp

---

src/instructions/port.rs
src/lib.rs
src/structures/paging/page.rs

The constant is Sealed::DEBUG_STR was also already exposed to users in its subtraits, but due to Sealed being unnamable reading DEBUG_STR was somewhat difficult. Moving the associated constants from the supertrait into the subtraits isn't a breaking change and makes it a bit more convenient to reference.
Fixes #470

expose DEBUG_STR more directly

---

src/registers/control.rs

If Cr4.PCID is set and the 63rd bit is clear when moving into Cr3, the processor flushes all TLB entries for the given PCID (Intel SDM, Volume 3, 4.10.4.1 and AMD APM, Volume 2, 5.5.1). This is similar to the operation without PCID in which the processor also flushes all TLB entries every time a new value is moved into Cr3. Given that the entire idea behind PCIDs is to not flush all entries when Cr3 is changed, we should also provide a write method that sets the 63rd bit when moving into Cr3. This PR adds `write_pcid_no_flush` to do just that.
A very quick and dirty comparison between `write_pcid` and `write_pcid_no_flush` showed a ~~10%~~ 25+% performance improvement.
It could be argued that setting the 63rd bit should be the default, however, I'm a bit concerned that users rely on the …

add write_pcid_no_flush

---

src/structures/gdt.rs

As mentioned in another pull request, the form for this function was preferred over the other implementation.
#406

Implement function for creating a gdt in a const environment.

---

src/instructions/port.rs

With this PR you can find `PortRead::read_from_port` and `PortWrite::write_to_port` via `in{,b,w,l}` and `out{,b,w,l}` respectively.

docs: add aliases for `in{,b,w,l}` and `out{,b,w,l}`

---

.github/workflows/build.yml

[actions-rs](https://github.com/actions-rs) has not been maintained for years and causes warnings:
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: migrate away from unmaintained actions

---

rust-toolchain
rust-toolchain.toml

See [The toolchain file - Overrides - The rustup book](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file).

chore: migrate from legacy `rust-toolchain` to `rust-toolchain.toml`

---

.github/workflows/build.yml

In d3b9c0573800b2e888486037e09d43ffd3ffcb97, we switched our test framework to the built-in x86_64-unknown-none target. This required a `-Crelocation-model=static` flag to work with bootloader v0.9, which we set using a `build.rustflags` config key.
In 2eb838d101cdd179d6395f79f87916a48e8c1935, we set a `RUSTFLAGS` env variable on CI to deny warnings.
Unfortunately, the above two commits conflict because the `RUSTFLAGS` env variable [takes precedence](https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags) over the `build.rustflags` key. This commit fixes this by setting an explicit `RUSTFLAGS` value for the bootloader test job that contains both flags.
This should fix the CI [build errors](https://github.com/rust-osdev/x86_64/actions/runs/8594672305/job/23548107284).

CI: Set `-Crelocation-model=static` in `RUSTFLAGS` for bootloader test job

---

src/structures/idt.rs

The lint exists to warn about incompatibilities with different architectures, but this code only runs on x86-64 anyway, so portability is not a concern.
This fixes a nightly breakage.

silence warning about cast

---

.github/workflows/build.yml
src/instructions/mod.rs
src/registers/control.rs
src/registers/debug.rs
src/registers/mod.rs
src/registers/model_specific.rs
src/registers/mxcsr.rs
src/registers/rflags.rs
src/registers/xcontrol.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mod.rs

A build on non-x86_64 platforms with the `instructions` feature enabled should not results in lots of inline assembly errors.
Implements option 3 described in https://github.com/rust-osdev/x86_64/pull/482#discussion_r1580529125.
Fixes the CI build error on `macos-latest`, which uses an ARM-based runner now.

Only enable instructions on `x86_64`

---

Changelog.md
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/mod.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

Add a way to clear page table entries that don't have the present flag set. 
See #481 for an explanation
fixes: #481

add Mapper::clear to clear any page table entry regardless of present flag

---

src/registers/model_specific.rs
src/structures/idt.rs

This PR fixes some warnings for lints recently added to clippy.

fix warnings

---

src/addr.rs
src/structures/paging/frame.rs

This PR makes `PhysFrame::from_start_address` and `PhysFrame::containing_address` const.

constify PhysFrame functions

---

src/structures/paging/page.rs

`Page<S>` only implements `Hash` if `S` also implements `Hash`. Not sure why this is a requirement since `size` is a `PhantomData`. 
This PR adds `Hash` implementations for `Size4KiB`, `Size2MiB` and `Size1GiB`.
I'm not 100% sure whether this is a breaking change or not. I can never remember if adding a trait is one or not. I am happy to rebase this onto next. Should be a trivial change anyways.

Ensure that Page actually implements Hash

---

src/instructions/segmentation.rs

Starting with the latest nightly, this results in an error:
```
error: avoid using labels containing only the digits `0` and `1` in inline assembly
--> src/instructions/segmentation.rs:81:18
|
81 |                 "1:",
|                  ^ use a different label that doesn't start with `0` or `1`
|
= note: an LLVM bug makes these labels ambiguous with a binary literal number
= note: `#[deny(binary_asm_labels)]` on by default
```

don't use label starting with `1`

---

src/lib.rs

This feature will be stable as of Rust 1.80 and so enabling it explicitly throws a warning. This PR fixes builds on the latest nightly version.

remove #![feature(asm_const)]

---

src/instructions/mod.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs

- Break long doc paragraph
- Elide explicit lifetimes when possible
Builds on top of #501, should be merged afterwards.

Fix clippy warnings

---

src/instructions/tlb.rs

Both Intel's and AMD's manuals describe the INVPCID descriptor as a 128-bit value with the linear address stored in the upper half and the PCID stored in the lower half. x86 uses little-endian byte ordering and so the lower half (pcid) should be stored before the upper half (address). Previously, our `InvpcidDescriptor` type stored the halves in the opposite order with the address before the pcid.
This patch fixes the order, so that the pcid is stored before the address. This new order is also the order used by Linux and OpenBSD:
https://github.com/torvalds/linux/blob/3e5e6c9900c3d71895e8bdeacfb579462e98eba1/arch/x86/include/asm/invpcid.h#L8
https://github.com/openbsd/src/blob/4e368faebf86e9a349446b5839c333bc17bd3f9a/sys/arch/amd64/include/cpufunc.h#L173
It's beyond me how this wasn't …

fix field order for INVPCID descriptor

---

.github/workflows/build.yml
src/structures/gdt.rs

It turns out that dtolnay/rust-toolchain sets the installed toolchain as the global default, but rustup prioritizes our rust-toolchain.toml. Instead, set an environment variable. RUSTUP_TOOLCHAIN has a higher priority than rust-toolchain.toml [^1].
[^1]: https://rust-lang.github.io/rustup/overrides.html#overrides

fix CI job for building on MSRV

---

src/structures/idt.rs

There is currently no way to create an instance of idt::ExceptionVector having an interrupt number. At the same time it would be convenient for the user to use this enum to handle interrupts.
As for the implementation, I couldn't think of what type of error it should return.

TryFrom implementation for ExceptionVector

---

src/structures/mod.rs

limit in gdtr contain size - 1

Minor clarification DescriptorTablePointer::limit comment

---

.github/workflows/build.yml
src/addr.rs
src/instructions/tlb.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs

A recent nightly changed the signature of `Step::steps_between` to match the signature of `Iterator::size_hint`. This PR changes our implementations to match the new signature. This PR also fixes the `Step` implementation of `Page` on 32-bit platforms.
Closes #512
Cc @isaka-james @tsatke

fix signature of Step::steps_between implementations

---

.github/workflows/build.yml
.github/workflows/release.yml
Cargo.toml
Changelog.md
src/addr.rs
src/instructions/segmentation.rs
src/instructions/tlb.rs
src/structures/paging/page.rs

We need to backport #513 to v0.14 because there are a lot of people still depending on v0.14 and it's currently broken on nightly.
I created a new branch `x86_64-0.14.x` to use for backporting fixes. This branch currently points at the commit that released v0.14.12 (the last commit before we started merging v0.15 stuff into master). I enabled branch protections on this new branch. This PR targets that new branch.
The first commit in this PR adjusts CI to run on the new branch so that our CI pipeline can create the release.
For the second commit, I cherry-picked b9e3d259ef84868c757c809c7d04c6d4bccfa402. This commit contains the fixes for newer nightlies. For the third commit, I cherry-picked 3fec974dadc45b7cf2507af1937fe95eb42ecb1e to fix a deny-by-default warning. Note that this PR …

backport #513

---

.github/workflows/build.yml
Cargo.toml
Changelog.md
src/addr.rs
src/instructions/mod.rs
src/instructions/segmentation.rs
src/instructions/tlb.rs
src/lib.rs
src/registers/model_specific.rs
src/structures/gdt.rs
src/structures/idt.rs
src/structures/mod.rs
src/structures/paging/frame.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/offset_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/page.rs
src/structures/paging/page_table.rs
src/structures/tss.rs
testing/src/gdt.rs

This PR syncs next with the changes on master. The only merge conflict was the changelog.

Merge master into next

---

src/structures/idt.rs

When running this test (debug-printing an empty IDT) without the fix, there is a panic:
```console
running 1 test
[src/structures/idt.rs:1725:9] InterruptDescriptorTable::new() = InterruptDescriptorTable {
divide_error: Entry {
handler_addr: 0x0,
options: EntryOptions {
code_selector: SegmentSelector {
index: 0,
rpl: Ring0,
},
thread 'structures::idt::test::idt_fmt_debug' panicked at src/structures/idt.rs:1006:9:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test structures::idt::test::idt_fmt_debug ... FAILED
```
This is because `EntryOptions::stack_index` subtracts one from the corresponding bits, which are zero for `EntryOptions::minimal`.
This fix inlines `EntryOptions::stack_index` into the `fmt::Debug` implementation …

fix(idt): panic in `impl fmt::Debug for EntryOptions`

---

src/structures/paging/mapper/mod.rs

This PR adds a way to get the page to be flushed from a `MapperFlush` instance. This is needed for multiple CPUs to perform the flush.

Add `MapperFlush` method to get page

---

src/registers/control.rs
src/registers/debug.rs
src/registers/model_specific.rs
src/registers/mxcsr.rs
src/registers/rflags.rs
src/registers/xcontrol.rs

This adds `update()`, akin to `update()` on `Cr0`, `Cr4`, and `Efer` to the following types/modules:
- `Cr3`
- `Dr7`
- `SFMask`
- `UCet`
- `SCet`
- `mxcsr`
- `rflags`
- `XCr0`

feat: add `update()` to `Cr3`, `Dr7`, `SFMask`, `UCet`, `SCet`, `mxcsr`, `rflags`, and `XCr0`

---

src/registers/model_specific.rs

This makes `FsBase::write()`, `GsBase::write()`, and `KernelGsBase::write()` unsafe and applies the safety doc comment from `Segment64::write_base()`.
Closes https://github.com/rust-osdev/x86_64/issues/526.

fix(model_specific): make `{Fs,Gs,KernelGs}Base::write()` unsafe

---

.github/workflows/build.yml
src/registers/segmentation.rs
src/registers/xcontrol.rs
src/structures/idt.rs

This PR fixes a couple of warnings and removes maco-12 from a matrix job (macos-12 has been removed).

fix warnings & remove broken CI job

---

src/registers/model_specific.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/page_table.rs

This adds support for the page attribute table MSR, and allows level 1 page table entries to have the `HUGE_PAGE` bit set. The `HUGE_PAGE` bit is used as the `PAT` bit to index the table for 4KiB pages.

Add page attribute table support

---

.github/workflows/release.yml

Currently, ubuntu-latest is ubuntu-24.04. ubuntu-24.04 ships with python 3.12 which is newer than python 3.11 (the version we previously manually installed).
On another happy note, cargo-semver-checks seems to have updated to a newer nightly and that fixed one of our CI jobs. Right now, none of the CI jobs should be broken anymore, all of them should pass :)

use default python again

---

src/registers/model_specific.rs

The **IA32_APIC_BASE** model-specifc register is for the configuration of the [Advanced Programmable Interrupt Controller.](https://wiki.osdev.org/APIC) This addition provides support for interacting with this MSR, since it is frequently used in modern OS development.
More information can be found in the [Intel® 64 and IA-32 Architectures Software Developer’s Manual Volume 3 (3A, 3B, 3C, & 3D): System Programming Guide](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html) in section **11.4.4 Local APIC Status and Location**

feat(msr): add IA32_APIC_BASE support

---

src/addr.rs

Use checked arithmetic for addition and subtraction of `VirtAddr` and `PhysAddr`, and add tests to confirm that they do, indeed, panic on arithmetic overflow/underflow.
They already panic on invalid addresses as a result of addition or subtraction, which means that this is hopefully the last piece needed to close #290

Ensure that addition and subtraction of addresses panics on overflow/underflow

---

.github/workflows/build.yml

The bootloader integration tests recently started failing on Linux and Windows because of this. I think Rust probably ought to support this, but there's also no good reason for us to do this.

don't pass -Crelocation-model=static to host targets

---

src/addr.rs

This PR improves the panic messages and documentation for `VirtAddr`'s `Add`/`Sub` impls.
Cc @tsatke
Closes #541

improve `VirtAddr` `Add` & `Sub` impls

---

src/registers/model_specific.rs
src/structures/paging/mapper/mapped_page_table.rs
src/structures/paging/mapper/recursive_page_table.rs
src/structures/paging/page_table.rs

This PR reverts #529 due to the concerns about breaking behavior listed in #538. We'll reintroduce the PR on the next branch. Once this PR has been merged, we'll merge master into next, then cherry-pick #529 onto the next branch, and potentially implement some of the improvements mentioned in #538.
@ChocolateLoverRaj I apologize for the delay, this has been sitting on top of my to-do list for way too long 😅
Cc @adavis628

Revert #529 on master
