rust-osdev/x86_64

- Cargo.toml
- src/lib.rs
- src/structures/paging/mod.rs
See https://github.com/rust-osdev/os_bootinfo/pull/2
> Add From/Into implementations for os_bootinfo::FrameRange

- src/structures/idt.rs
> Fix for #36 

- testing/Cargo.toml
- testing/x86_64-bare-metal.json
This should fix the travis build.
> Update test to latest bootimage

- src/instructions/port.rs
Using correct register sizes.
Cannot test this beyond confirming it compiles.
> Fix port read/write asm

- Cargo.toml
- Changelog.md
- src/instructions/interrupts.rs
- src/instructions/port.rs
- src/instructions/segmentation.rs
- src/instructions/tables.rs
- src/instructions/tlb.rs
- src/lib.rs
- src/registers/control.rs
- src/registers/model_specific.rs
- src/registers/rflags.rs
- src/structures/gdt.rs
- src/structures/idt.rs
- src/structures/paging/frame_alloc.rs
- src/structures/paging/mod.rs
- src/structures/paging/page_table.rs
- src/structures/paging/recursive.rs
- src/structures/tss.rs
> Prepare for version 0.4.0

- Cargo.toml
- src/instructions/mod.rs
- src/lib.rs
- src/random/mod.rs
Related issue: #56
Work in progress
> Support for RdRand

- .github/workflows/build.yml
- bors.toml
- rust-toolchain
This pull request switches the continuous integration provider from Azure Pipelines to GitHub Actions.
> Switch to GitHub Actions for CI

- bors.toml
See https://github.com/rust-osdev/x86_64/pull/102#issuecomment-564001856 and https://github.com/rust-osdev/x86_64/pull/99#issuecomment-564002172
> Remove bors from this repo

- src/addr.rs
> Update docs to suggest `TryFrom` trait

- Cargo.toml
- Changelog.md
This creates a new patch release with the changes added in the past month (see the changelog updates).
TODO after merging:
> Release version 0.12.3

- src/structures/paging/page_table.rs
> feat: implement `Clone` for `PageTable`

- Changelog.md
- src/structures/idt.rs
> Fix Debug and PartialEq implementations for IDT entry type

- scripts/ci-release.py
Instead of listing all versions, try to query the info about the respective version directly.
Also: Some formatting improvements.
Proposed in https://github.com/rust-osdev/x86_64/pull/281#discussion_r672091911
> CI: Use more efficient crates.io API endpoint

- src/structures/gdt.rs
I also tried to fix the broken intra links but couldn't.
> fix(gdt): typo

- Cargo.toml
- Changelog.md
> Release version 0.14.6

- src/structures/paging/page.rs
Oops, that's embarrassing for me.
> fix docs for `page_table_index`

- Cargo.toml
- Changelog.md
> Bump version to 0.14.8

- .github/workflows/build.yml
- Cargo.toml
- README.md
- src/structures/idt.rs
- src/structures/paging/mapper/mod.rs
- src/structures/tss.rs
This requires merging in master to get #355
> Update "next" MSRV to 1.59

- Cargo.toml
- Changelog.md
This isn't quite ready, I think we still want to wait on #366, #362, and #369
~~I also still have to write the changelog.~~ Done
> Release 0.14.9

- .github/workflows/build.yml
- .github/workflows/release.yml
Uses the [`cargo-semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) tool to check for violations of semver.
> Check for breaking changes on CI

- Cargo.toml
- Changelog.md
This PR prepares the v0.15.0 stable release.
> release v0.15.0

- Cargo.toml
- Changelog.md
This PR prepares the 0.15.1 release.
CC @GZTimeWalker
> release 0.15.1

- testing/src/gdt.rs
This PR fixes a warning that occurs in newer nightlies.
> fix testing

- Cargo.toml
- Changelog.md
This PR creates a release. Notably, this PR includes fixes for a recent nightly breakage.
> release 0.15.2

- .github/workflows/build.yml
Ubuntu 20.04 has been retired.
> fix kani build job
